<?php

namespace AppBundle\Repository;

/**
 * ModelRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
