<?php

namespace AppBundle\Repository;

/**
 * MoveOutRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveOutRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
