<?php

namespace AppBundle\Repository;

/**
 * MoveOutRoomObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveOutRoomObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
