<?php

namespace AppBundle\Repository;

/**
 * MoveOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveOutRepository extends \Doctrine\ORM\EntityRepository
{
}
