<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends EntityRepository
{
    public function getObjectLike($object)
    {
        $object = $object . "%";
        $qb = $this->createQueryBuilder('o')
            ->select('o.object')
            ->where('o.object = :object')
            ->andWhere('o.object LIKE :object')
            ->setParameter('object', $object)
            ->getQuery();
        return $qb->getResult();
    }
}
