<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectRepository extends EntityRepository
{
    public function getObjectLike($name)
    {
        $qb = $this->createQueryBuilder('o')
            ->select('o.name', 'o.id')
            ->where('o.name LIKE :name')
            ->setParameter('name', $name.'%')
            ->getQuery();
        return $qb->getResult();
    }
}
