<?php

namespace AppBundle\Repository;

/**
 * PanelRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanelRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
